# Generated by Django 5.0.1 on 2024-01-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
