# Generated by Django 5.0.1 on 2024-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_rename_f_name_subscribe_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly')], default='W',
                                   max_length=1),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='message',
            field=models.TextField(),
        ),
    ]
