# Generated by Django 5.0.1 on 2024-01-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscribe_option_alter_subscribe_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly')], default='M',
                                   max_length=1),
        ),
    ]
