# Generated by Django 5.0.1 on 2024-01-13 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateTimeField
            (auto_now_add=True, default=datetime.datetime
                (2024, 1, 13, 10, 36, 42, 444128,
                 tzinfo=datetime.timezone.utc), verbose_name='Date Posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Salary'),
            preserve_default=False,
        ),
    ]
