# Generated by Django 5.0.1 on 2024-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
    ]
