# Generated by Django 5.0.1 on 2024-01-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skills_jobpost_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Country'),
        ),
    ]
