# Generated by Django 5.0.1 on 2024-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_skills_skill_alter_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')],
                                   max_length=200, verbose_name='job_type'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
